In [23]:
import torch
from torch.autograd import Variable
import numpy as np

In [6]:
x = torch.Tensor(np.eye(10))

x


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
from Autoencoders import GaussianDistribution


In [9]:
dis = GaussianDistribution(1, torch.Tensor([0]), torch.Tensor([1]))


In [47]:

x = dis()

In [48]:
loss = Variable(x - torch.Tensor(1), requires_grad=True)

In [49]:
loss.backward()


In [50]:
x.grad()


TypeError: 'NoneType' object is not callable

In [28]:
d = dis()
print(d)
print(d - torch.Tensor([2]))

tensor([[-0.0058]])
tensor([[-2.0058]])


In [31]:
loss.gradient()

AttributeError: 'Tensor' object has no attribute 'gradient'

In [67]:
rands = torch.rand(10)
m = torch.nn.Linear(10, 2)
print(rands)
params = m(rands)
print(f"{params} are the params ")
print(f"Params [0] are {params[0]} and Params[1] are {params[1]}")
dis = torch.distributions.Normal(params[0], params[1])
sample = dis.rsample()
print(sample)
loss = torch.square(sample - torch.Tensor(1))
print(loss)
loss.backward()
print("Weights are given by")
print(m.weight)
print("weights' grads are given by ")
print(m.weight.grad)

tensor([0.3141, 0.6976, 0.3728, 0.8627, 0.8665, 0.1146, 0.6472, 0.3583, 0.5414,
        0.2935])
tensor([0.3007, 0.1815], grad_fn=<AddBackward0>) are the params 
Params [0] are 0.30067312717437744 and Params[1] are 0.18150267004966736
tensor(0.1007, grad_fn=<AddBackward0>)
tensor([0.0101], grad_fn=<PowBackward0>)
Weights are given by
Parameter containing:
tensor([[ 0.0157,  0.2689,  0.1617,  0.0984, -0.1073, -0.1673,  0.3065, -0.0853,
          0.1946, -0.1132],
        [-0.0397, -0.1207,  0.2254,  0.0898, -0.1293,  0.2476, -0.0452, -0.0517,
         -0.1306,  0.0415]], requires_grad=True)
weights' grads are given by 
tensor([[ 0.0633,  0.1405,  0.0751,  0.1738,  0.1746,  0.0231,  0.1304,  0.0722,
          0.1091,  0.0591],
        [-0.0697, -0.1548, -0.0827, -0.1915, -0.1923, -0.0254, -0.1436, -0.0795,
         -0.1201, -0.0651]])
