In [36]:
%reload_ext autoreload
%autoreload 2

In [60]:
import torch
from torch.autograd import Variable
from torch import nn
import numpy as np
from Autoencoders import GaussianDistribution

In [48]:
x = torch.Tensor(np.eye(10))

x


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [115]:
lin = nn.Linear(1, 2)
initial = torch.Tensor([0.5])

In [116]:
params = lin(initial)
print(params)
print(params[0], params[1])
print(params[0].shape, params[1].shape)

params[1:2].size(), params[0:1].size()


tensor([0.5294, 0.6248], grad_fn=<AddBackward0>)
tensor(0.5294, grad_fn=<SelectBackward0>) tensor(0.6248, grad_fn=<SelectBackward0>)
torch.Size([]) torch.Size([])


(torch.Size([1]), torch.Size([1]))

In [117]:
distrib = GaussianDistribution((1, 0), params[0:1], params[1:2])
x = distrib()

print(x)


# distrib = torch.distributions.Normal(params[0:1], scale=params[1:2])
# x = distrib.rsample()

tensor([[0.6445]], grad_fn=<AddBackward0>)


In [118]:
# loss = Variable(x - torch.Tensor(1), requires_grad=True)
loss = torch.square(x - torch.Tensor([1]))

In [119]:
loss.backward()


In [120]:
lin.weight


Parameter containing:
tensor([[0.6092],
        [0.9111]], requires_grad=True)

In [121]:
print(lin.weight.grad)

tensor([[-0.3555],
        [-0.0655]])


In [122]:
d = dis()
print(d)
print(d - torch.Tensor([2]))

NameError: name 'dis' is not defined

In [ ]:
loss.gradient()

AttributeError: 'Tensor' object has no attribute 'gradient'

In [ ]:
rands = torch.rand(10)
m = torch.nn.Linear(10, 2)
print(rands)
params = m(rands)
print(f"{params} are the params ")
print(f"Params [0] are {params[0]} and Params[1] are {params[1]}")
dis = torch.distributions.Normal(params[0], params[1])
sample = dis.rsample()
print(sample)
loss = torch.square(sample - torch.Tensor(1))
print(loss)
loss.backward()
print("Weights are given by")
print(m.weight)
print("weights' grads are given by ")
print(m.weight.grad)

tensor([0.3141, 0.6976, 0.3728, 0.8627, 0.8665, 0.1146, 0.6472, 0.3583, 0.5414,
        0.2935])
tensor([0.3007, 0.1815], grad_fn=<AddBackward0>) are the params 
Params [0] are 0.30067312717437744 and Params[1] are 0.18150267004966736
tensor(0.1007, grad_fn=<AddBackward0>)
tensor([0.0101], grad_fn=<PowBackward0>)
Weights are given by
Parameter containing:
tensor([[ 0.0157,  0.2689,  0.1617,  0.0984, -0.1073, -0.1673,  0.3065, -0.0853,
          0.1946, -0.1132],
        [-0.0397, -0.1207,  0.2254,  0.0898, -0.1293,  0.2476, -0.0452, -0.0517,
         -0.1306,  0.0415]], requires_grad=True)
weights' grads are given by 
tensor([[ 0.0633,  0.1405,  0.0751,  0.1738,  0.1746,  0.0231,  0.1304,  0.0722,
          0.1091,  0.0591],
        [-0.0697, -0.1548, -0.0827, -0.1915, -0.1923, -0.0254, -0.1436, -0.0795,
         -0.1201, -0.0651]])


In [ ]:
NUM_LATENT = 10


dis = GaussianDistribution(shape=(10,1), mu=torch.Tensor(np.zeros()), sigma=torch.Tensor(np.eye(10)))